Made civvie research less grindy.
ilikeships/Hullrot-YAML-Prototypes pull request #13
Opened 2024-12-02 03:27 UTC by Ophanimdev

Reduced civilian research prices all around because it's rather ridiculous to have to pay 10k research points just to figure out what a MICROWAVE is. 

This should make the civilian research grindset a lot shorter and therefore empower people to actually enjoy the game rather than fondle an obese, latex-wearing, unemployed western Canadian's """vision"""

2024-12-02 08:43 UTC, MLGTASTICa requested changes

2024-12-02 08:43 UTC, MLGTASTICa commented on Research/industrial.yml
> +  cost: 500 #You can get most of these items from vending machines and there's like 50 of them in a given machine
This is a vital research. Bring it back to 7.5k

2024-12-02 08:43 UTC, MLGTASTICa commented on Research/civilianservices.yml
> +  cost: 6666 #Made for centisyzing feotuses
remove this comment , against github tos bro

2024-12-02 08:43 UTC, MLGTASTICa commented on Research/industrial.yml
> +  cost: 2500
keep at original cost. this unlocks thrusters

2024-12-02 14:18 UTC, Ophanimdev commented
Well, I was under the impression that R&D as is would be eventually scrapped and is more of a placeholder feature at the moment. But, very well.

2024-12-04 22:41 UTC, MLGTASTICa requested changes

2024-12-04 22:41 UTC, MLGTASTICa commented on _Crescent/Entities/Objects/Misc/liquidcontainers.yml
> +  description: Petroleum has always been produced from organic beings. This liquid has always been made from the fear, pleasure, grief, loathing, and resentment of living creatures!
boriatic fuel is not petroluem , lore check fail!!!

2024-12-04 23:35 UTC, Ophanimdev commented
It's done.

2024-12-05 14:26 UTC, Boltersam commented
> It's done. But could you clarify the nature of boriatic fuel? The word doesn't seem to actually mean anything and the only reference I could find to it were the following links: https://tardis.fandom.com/wiki/Boriatic_Wastes https://forums.spacebattles.com/threads/sector-crescent-hullrot.1179364/

It's a volatile liquid fuel that explodes when the container/engine is damaged, or ignites when a puddle is heated - effectively space gasoline. It's the most ubiquitous and cheap form of fuel, usually for small or jury-rigged ships

Actual nature & origin is undefined since fuel refining was removed to be readded later, name is gibberish

2024-12-05 19:20 UTC, merged