Oni Melee Overhaul
ilikeships/Hullrot-YAML-Prototypes pull request #9
Opened 2024-12-02 01:47 UTC by Ophanimdev

I've been told that Oni are rather weak and a shite pick in a game where most people have guns and have a rather large front and side profile that lends to them being rather easy targets. Especially when they can't actually shoot back due to their genetics. All right, I say. I'll overtune the Melee race into being a decent pick, and so I have. 

To that end I've added following 'abilities' to Oni:

1. Their punches do real good damage and have a real low cooldown. (Firing a gun's still probably faster.)
2. The lower their health gets, the faster they get, until they're zooming all over the place. They're also quite faster than a base human, too. This is so they can actually close the distance between them and their opponents.
3. They're slightly smaller than their old size, but still larger than a human. 

I think these changes'd make Oni a race people'll actually pick rather than simply ignore save for meme rounds where guns are scarce and melee is king.

2024-12-02 09:48 UTC, MLGTASTICa requested changes

2024-12-02 09:48 UTC, MLGTASTICa commented on Nyanotrasen/Datasets/Names/pitbull.yml
> +  - Childkiller
cringe , remove this.

2024-12-02 09:48 UTC, MLGTASTICa commented on Nyanotrasen/Entities/Mobs/Species/oni.yml
> +          radius: 0.38
keep the hitbox big they are huge.

2024-12-02 14:13 UTC, Ophanimdev commented
'tis done my liege.

2024-12-02 17:18 UTC, a-person5660 commented
>base oni faster than felinid

at least make felinid faster too so they arent just a weaker human lol

2024-12-03 14:41 UTC, SixplyDev commented
Why lol, I liked oni when they were big hulking brutes that used melee to their advantage. This is just making them a more powerful felinid atp. If people aren't playing onis right then that's on them.

2024-12-03 15:00 UTC, MLGTASTICa requested changes

2024-12-03 15:00 UTC, MLGTASTICa commented on Nyanotrasen/Entities/Mobs/Species/oni.yml
> -    scale: 1.2, 1.2
bring back size

2024-12-03 15:00 UTC, MLGTASTICa commented on Nyanotrasen/Entities/Mobs/Species/oni.yml
> +    attackRate: 4
reduce this to default , this is too much DPS for melee.

2024-12-03 18:14 UTC, ilikeships commented
good to merge once you fulfill MLG's requests

2024-12-03 18:37 UTC, Ophanimdev commented
They've been fulfilled, my liege.

2024-12-03 18:44 UTC, ilikeships commented
@MLGTASTICa

2024-12-03 22:28 UTC, GroggleG commented
"Hmmm this race seems a bit weak, lets tweak it asthough it is a weapon" Buddy...

2024-12-06 12:14 UTC, MarioDeez commented
> Why lol, I liked oni when they were big hulking brutes that used melee to their advantage. This is just making them a more powerful felinid atp. If people aren't playing onis right then that's on them.

Onis are dogshit because meelee is dogshit. They needed the speedbuff as otherwise people can just fucking run away from them while gunning them down, ambushes just dont work because people dont get slowed down immediately while in meelee or some other mechanics that make it viable.

2024-12-07 02:15 UTC, Ophanimdev commented
https://www.youtube.com/watch?v=4H4-BagR3hs

2024-12-09 22:45 UTC, Boltersam commented
> > Why lol, I liked oni when they were big hulking brutes that used melee to their advantage. This is just making them a more powerful felinid atp. If people aren't playing onis right then that's on them.
> 
> Onis are dogshit because meelee is dogshit. They needed the speedbuff as otherwise people can just fucking run away from them while gunning them down, ambushes just dont work because people dont get slowed down immediately while in meelee or some other mechanics that make it viable.

I agree with this sentiment personally
I believe the goal would be to make Oni 'the best' at melee, rather than the only viable way to play melee
In my opinion the increased speed when wounded is a great pick for buffing oni specifically, but the general minor movespeed buff would be better placed on onehanded melee weapons in general rather than relegated to one race

2024-12-13 21:37 UTC, MLGTASTICa commented
Ive decided that Oni in their current state do not really need a buff.

2024-12-13 21:37 UTC, closed without merging